name: PR Commenter

on:
  pull_request:
    types: [opened]

jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
    - name: Add comment to PR
      uses: actions/github-script@v6
      with:
        script: |
          const issue_number = context.payload.pull_request.number;
          const comment = "Please update doxygen documentation if required.";
          github.rest.issues.createComment({...context.repo,
            issue_number,
            body: comment});