name: PR Commenter

on:
  pull_request:
    types: [opened]

jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add comment to PR
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Please update doxygen documentation if required.
