name: Update PR Title with Full Commit Message

on:
  pull_request:
    types: [opened]

jobs:
  update-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get full commit message
        id: commit
        run: |
          MESSAGE=$(git log -1 --pretty=%B)
          echo "message<<EOF" >> $GITHUB_OUTPUT
          echo "$MESSAGE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Update PR title using PAT
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT1 }}
          script: |
            const fullMessage = `${{ steps.commit.outputs.message }}`.trim();
            github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              title: fullMessage
            });

