name: Update PR Title If Truncated  
 
on:  
  pull_request:  
    types: [opened, edited, reopened]  
 
jobs:  
  update-pr-title:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Update PR Title if Truncated  
        uses: actions/github-script@v6  
        with:  
          script: |  
            const { github, context } = require('@actions/github');  
 
            // Gather owner, repo, pull number from context  
            const owner = context.repo.owner;  
            const repo = context.repo.repo;  
            const pull_number = context.payload.pull_request.number;  
 
            // Fetch all commits for this PR  
            const { data: commits } = await github.rest.pulls.listCommits({  
              owner,  
              repo,  
              pull_number  
            });  
 
            // We only want to act if there's exactly 1 commit  
            if (commits.length !== 1) {  
              console.log("PR has more than 1 commit (or zero). Doing nothing.");  
              return;  
            }  
 
            const commitMessage = commits[0].commit.message;  
            const currentTitle = context.payload.pull_request.title;  
 
            // If the commit message is not longer than 70 chars,  
            // GitHub won’t auto-truncate it in the PR title.  
            if (commitMessage.length <= 70) {  
              console.log("Commit message <= 70 chars. Doing nothing.");  
              return;  
            }  
 
            // GitHub typically truncates to the first 70 chars + "..."  
            const truncated = commitMessage.slice(0, 70) + "...";  
 
            // Check if the current PR title matches that truncated form  
            if (currentTitle === truncated && currentTitle !== commitMessage) {  
              console.log("Detected truncated PR title. Updating to full commit message...");  
              await github.rest.pulls.update({  
                owner,  
                repo,  
                pull_number,  
                title: commitMessage  
              });  
            } else {  
              console.log("Title is not auto-truncated or already updated. Doing nothing.");  
            } 
